// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CompanyAddressAutocompleteController from "./company_address_autocomplete_controller"
application.register("company-address-autocomplete", CompanyAddressAutocompleteController)

import DisplaySuggestionsController from "./display_suggestions_controller"
application.register("display-suggestions", DisplaySuggestionsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NewMsgNotifController from "./new_msg_notif_controller"
application.register("new-msg-notif", NewMsgNotifController)

import PaymentController from "./payment_controller"
application.register("payment", PaymentController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TsparticlesController from "./tsparticles_controller"
application.register("tsparticles", TsparticlesController)

import VenuemapController from "./venuemap_controller"
application.register("venuemap", VenuemapController)
